export const ACCOUNT_SIGNUP_REQUESTED = 'ACCOUNT_SIGNUP_REQUESTED';
export const ACCOUNT_SIGNUP_SUCCESSED = 'ACCOUNT_SIGNUP_SUCCESSED';
export const ACCOUNT_SIGNUP_FAILED = 'ACCOUNT_SIGNUP_FAILED';

export const ACCOUNT_SIGNIN_REQUESTED = 'ACCOUNT_SIGNIN_REQUESTED';
export const ACCOUNT_SIGNIN_SUCCESSED = 'ACCOUNT_SIGNIN_SUCCESSED';
export const ACCOUNT_SIGNIN_FAILED = 'ACCOUNT_SIGNIN_FAILED';
