export const CLIPBOARD_ADD_REQUESTED = 'CLIPBOARD_ADD_REQUESTED';
export const CLIPBOARD_ADD_SUCCESSED = 'CLIPBOARD_ADD_SUCCESSED';
export const CLIPBOARD_ADD_FAILED = 'CLIPBOARD_ADD_FAILED';

export const CLIPBOARDS_RECEIVE_REQUESTED = 'CLIPBOARDS_RECEIVE_REQUESTED';
export const CLIPBOARDS_RECEIVE_SUCCESSED = 'CLIPBOARDS_RECEIVE_SUCCESSED';
export const CLIPBOARDS_RECEIVE_FAILED = 'CLIPBOARDS_RECEIVE_FAILED';

export const CLIPBOARD_DELETE_REQUESTED = 'CLIPBOARD_DELETE_REQUESTED';
export const CLIPBOARD_DELETE_SUCCESSED = 'CLIPBOARD_DELETE_SUCCESSED';
export const CLIPBOARD_DELETE_FAILED = 'CLIPBOARD_DELETE_FAILED';

export const CLIPBOARD_EDIT_REQUESTED = 'CLIPBOARD_EDIT_REQUESTED';
export const CLIPBOARD_EDIT_SUCCESSED = 'CLIPBOARD_EDIT_SUCCESSED';
export const CLIPBOARD_EDIT_FAILED = 'CLIPBOARD_EDIT_FAILED';
