export const REQUEST_TEST = 'REQUEST_TEST';

export const FETCH_SERVER_INFO_REQUESTED = 'FETCH_SERVER_INFO_REQUESTED';
export const FETCH_SERVER_INFO_SUCCESSED = 'FETCH_SERVER_INFO_SUCCESSED';
export const FETCH_SERVER_INFO_FAILED = 'FETCH_SERVER_INFO_FAILED';
